# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &pc age1h72rxhnmvfp55rct4zj4frhuav0uf23sgre2e8qyrvqd3zu3x40swg0rhc
  - &klamm age19407phf8dyq8qm79pvxxnfvhn8chx4z4caz7w8yk89rlg6llucuqstpnpe
creation_rules:
  - path_regex: secrets/[^/]+
    key_groups:
    - age:
      - *pc
      - *klamm
